package connector;

import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Carlos Suarez Fontalvo Creating a client for Sharepoint Online.!
 * following source: https://github.com/lstak/node-sharepoint following article:
 * http://allthatjs.com/2012/03/28/remote-authentication-in-sharepoint-online/
 * following article: http://allthatjs.com/2012/03/29/node-js-meet-sharepoint/
 * following article: https://gist.github.com/2272889
 */
public class SharePointClient {

    //information for signin
    private String _tokenSPO;
    private String userName;
    private String password;
    private String SSLendPoint;
    //Cookie with final signin information
    private String cookieNedToken;
    //Location of SAM.xml template
    private static final String _samFileLocation;
    private static final Logger _log;

    static {
        _samFileLocation = Path.of(System.getProperty("user.dir"), "src", "META-INF", "SAML.xml").toString();
        _log = Logger.getLogger(SharePointClient.class.getName());
        _log.log(Level.INFO, "Creating Log Service for {0}", SharePointClient.class.getName());
    }

    /**
     * Default constructor for the SharePoint Client
     *
     * @param userName string with username, username@domain.com
     * @param password string with the password for the username submitted
     * @param endPoint string with the target to prepare de SAML file that is
     * going to be sended to the STS (Security Token Service).
     */
    public SharePointClient(String userName, String password, String endPoint) throws Exception {
        this._tokenSPO = _Constants.EXTSTS_SRF_URL;
        this.SSLendPoint = _Constants.DEFAULT_SSL_PROTOCOL + endPoint + _Constants.DEFAULT_LOGIN_PATH;
        this.userName = userName;
        this.password = password;
        this.signin();
    }

    /**
     * This method Send SAML Request to STS (Security Token Service) The
     * application POSTs an SAML Request Security Token message to the Microsoft
     * Online STS, located at the {@link #_tokenSPO}. It uses the already
     * formatted SAML.xml file.
     *
     * @param SAMLFile the content of the XML file with the initial structure
     * @return the securiy token, null if SAMLFile is malformed or STS is down.
     * @throws MalformedURLException
     * @throws IOException
     */
    private String firstPartSignin(String samlContent) throws MalformedURLException, IOException {

        URLConnection connection = new URL(this._tokenSPO).openConnection();
        connection.setDoOutput(true);
        connection.setRequestProperty("Accept-Charset", StandardCharsets.UTF_8.name());
        connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded;charset=" + StandardCharsets.UTF_8.name());
        connection.setRequestProperty("Content-Length", String.valueOf(samlContent.length()));
        try (OutputStream output = connection.getOutputStream()) {
            output.write(samlContent.getBytes(StandardCharsets.UTF_8));
        } catch (IOException ex) {
            throw new IOException(ex.getMessage(), ex);
        }

        //Printing the request generated by the Security Token Service (STS) and
        //Getting the token t=...
        String tokenT = null;
        try (BufferedReader resBuf = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
            String oString;
            while ((oString = resBuf.readLine()) != null) {
                int startTag = oString.indexOf("<wsse:BinarySecurityToken Id=\"Compact0\">");
                int endIndex = oString.indexOf("</wsse:BinarySecurityToken>");
                if (startTag != -1 && endIndex != -1) {
                    int beginIndex = startTag + ("<wsse:BinarySecurityToken Id=\"Compact0\">").length();
                    tokenT = oString.substring(beginIndex, endIndex);
                    _log.log(Level.CONFIG, tokenT);
                }
            }
        }

        return tokenT;
    }

    /**
     * This method sends the generated security token from the STS to the SPO
     * (SharePoint Online). {@link #SSLendPoint} Its includes a User-Agent
     * header to accomplish this task.
     *
     * @see connector._Constants.DEFAULT_USER_AGENT_WINDOWS for default
     * User-Agent
     * @param STSToken the security token previosly generated
     * @return connection with the cookies: FedAuth and rtFa
     * @throws MalformedURLException
     * @throws ProtocolException
     * @throws IOException
     */
    private HttpURLConnection secondPartSignin(String STSToken) throws MalformedURLException, ProtocolException, IOException {

        HttpURLConnection connection = (HttpURLConnection) new URL(this.SSLendPoint).openConnection();
        connection.setRequestMethod("POST");
        connection.setRequestProperty("User-Agent", _Constants.DEFAULT_USER_AGENT_WINDOWS);
        connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
        connection.setRequestProperty("Content-Length", STSToken.length() + "");
        // Necesary, URLConnection class doesn't support auto-redirect disabling.
        // @see: http://stackoverflow.com/questions/2659000/java-how-to-find-the-redirected-url-of-a-url for more information.
        // Tnx to Srinivas for pointing me in this direction.
        connection.setInstanceFollowRedirects(false);
        connection.setDoOutput(true);

        try (OutputStream output = connection.getOutputStream()) {
            output.write(STSToken.getBytes(StandardCharsets.UTF_8));
        } catch (IOException ex) {
            throw new IOException(ex.getMessage(), ex);
        }
        return connection;
    }

    /**
     * This method will generate a String with both FedAuth and rtFa cookie
     * values.
     *
     * @param connection object with cookies embbeded.
     * @return string with the both cookies values.
     * @throws Exception if connection object has invalid cookies format.
     */
    private String getCookieNedToken(HttpURLConnection connection) throws Exception {

        String _cookieNedToken = null;

        List<String> cookies = connection.getHeaderFields().get("Set-Cookie");
        String FedAuthCookie = null;
        String rtFaCookie = null;
        //Printing Authentication cookies
        for (String str : cookies) {
            if (str.contains("FedAuth")) {
                FedAuthCookie = str.split(" ")[0];
                _log.log(Level.CONFIG, FedAuthCookie);
            }
            if (str.contains("rtFa")) {
                rtFaCookie = str.split(" ")[0];
                _log.log(Level.CONFIG, rtFaCookie);
            }
        }

        if (FedAuthCookie == null || rtFaCookie == null) {
            throw new Exception("Invalid CookieNed Token!!!");
        } else {
            _cookieNedToken = FedAuthCookie + " " + rtFaCookie;
            _log.log(Level.CONFIG, "CookieNed Token {0}: ", _cookieNedToken);
            //cookieNedToken.addRequestProperty("Cookie", FedAuthCookie + " " + rtFaCookie);
        }

        return _cookieNedToken;
    }

    public String getCookieNedToken() {
        return this.cookieNedToken;
    }

    /**
     * This method will sign in the user into (SPO) SharePoint Online using
     * Claims-Based authentication.
     *
     * @throws Exception
     */
    private void signin() throws Exception {

        _log.log(Level.CONFIG, "SAML Template location at: {0}", _samFileLocation);



        try {
            //Read the SAML template and substitute placeholders
            String samlContent = Files.readString(Path.of(_samFileLocation), StandardCharsets.UTF_8)
                    .replace("[username]", this.userName)
                    .replace("[password]", this.password)
                    .replace("[endpoint]", this.SSLendPoint);

            //Executing the first part of the signin process
            String tokenT = firstPartSignin(samlContent);
            //Executing the second part of the signin process
            HttpURLConnection connection = secondPartSignin(tokenT);
            //Asigning final Token to variable
            this.cookieNedToken = getCookieNedToken(connection);

            _log.log(Level.CONFIG, "Username {0} successfully logged in. \nCookieNed value is: {1}", new Object[]{this.userName, this.cookieNedToken});

        } catch (IOException ex) {
            throw new Exception(ex.getMessage(), ex.getCause());
        }
    }
}